-- =====================================================
-- database: hxblog
-- postgresql 18+
--
-- 01. configuration - applications
-- =====================================================

create table if not exists "01_config_applications" (
    id int2 generated by default as identity primary key,
    code char(16) not null unique,
    description text not null
);

comment on table "01_config_applications" is 'stores application/microservices names';


insert into "01_config_applications" (id, code, description) values
(1, 'blog', 'tara blog');